### ISSUE TITLE
About implementation of this method

### ISSUE THREAD

**Issue by xzhatgeek** [pfmarteau/DiFF-RF#1]
Mr Marteau, I have read your article titled "Random Partitioning Forest for Point-Wise and Collective Anomaly Detection - Application to Network Intrusion Detection".  Here are some problems i have encountered while trying to run this program:
---------------------------------------------------------------------------------------------------------------------------------------------------
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
---------------------------------------------------------------------------------------------------------------------------------------------------
Please how to deal with this problem.

**Comment by pfmarteau** [comment]
Dear [xzhatgeek](https://github.com/xzhatgeek),
Can you be more specific about the occurrence of this error (what code do you execute exactly?). Meanwhile, I have modified slightly DiFF-RF.py to correct missing variable definitions.
Best

**Comment by xzhatgeek** [comment]
Thanks for the reply, I have solved the problem by running the program inside the main function but I still can't solve running the program outside the main function.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pfmarteau/DiFF-RF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月17日(星期四) 凌晨0:24
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [pfmarteau/DiFF-RF] About implementation of this method (Issue #1)





 
Dear xzhatgeek,
 Can you be more specific about the occurrence of this error (what code do you execute exactly?). Meanwhile, I have modified slightly DiFF-RF.py to correct missing variable definitions.
 Best
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
